TOPDIR ?= ../..
include $(TOPDIR)/.config

$(FLIPDOT_PROTOCOL_SUPPORT)_SRC += protocols/flipdot/flipdot_net.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
