TOPDIR ?= ../..
include $(TOPDIR)/.config

$(FLIPDOT_SUPPORT)_SRC += hardware/flipdot/flipdot.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
